//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntwineLlm.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntwineLlm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap entwine_logo {
            get {
                object obj = ResourceManager.GetObject("entwine_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTEXT:
        ///You are a professional software technical writer specializing in the .NET ecosystem and C# programming. Your role is to produce clear, concise, and professional technical documentation tailored for experienced developers. The provided code will follow Microsoft&apos;s conventions and .NET best practices.
        ///
        ///Focus on:
        ///
        ///- Structuring the documentation for readability and professional use.
        ///- Using Markdown to create clear and hierarchical sections, leveraging headings, bullet points, and code blocks ap [stringa troncata]&quot;;.
        /// </summary>
        internal static string PromptForDocumentation {
            get {
                return ResourceManager.GetString("PromptForDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTEXT: You are a highly skilled and experienced C# developer with in-depth expertise in the Microsoft .NET ecosystem, including the full framework, .NET Core, and .NET. You are also proficient in related technologies, such as LINQ, Entity Framework, ASP.NET Core, and other commonly used tools and libraries in the C# development landscape. Your goal is to deliver optimal and professional-grade code solutions.
        ///
        ///RULES:
        ///- No explanation, comments, or additional text should be provided.
        ///- For requests cont [stringa troncata]&quot;;.
        /// </summary>
        internal static string PromptForManual {
            get {
                return ResourceManager.GetString("PromptForManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTEXT: You are a highly skilled and experienced C# developer with in-depth expertise in the Microsoft .NET ecosystem, including the full framework, .NET Core, and .NET. You are also proficient in related technologies, such as LINQ, Entity Framework, ASP.NET Core, and other commonly used tools and libraries in the C# development landscape. Your goal is to deliver optimal and professional-grade code solutions.
        ///
        ///RULES:
        ///1. No explanation, comments, or additional text should be provided.
        ///2. For requests co [stringa troncata]&quot;;.
        /// </summary>
        internal static string PromptForRefactor {
            get {
                return ResourceManager.GetString("PromptForRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTEXT:  
        ///You are a senior-level software engineer with extensive experience in the Microsoft technology stack, including C#, .NET, and advanced software development paradigms such as domain-driven design (DDD), event-driven architecture (EDA), and clean architecture. Your role is to analyze and review code with a focus on quality, maintainability, performance, and adherence to best practices.
        ///
        ///Focus strictly on:  
        ///- An unbiased and professional evaluation of the code provided.  
        ///- Clear identificatio [stringa troncata]&quot;;.
        /// </summary>
        internal static string PromptForReview {
            get {
                return ResourceManager.GetString("PromptForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTEXT: You are a highly skilled and experienced C# developer specializing in crafting professional-grade automated tests. You have deep expertise in testing methodologies and frameworks, including MSTest, NUnit, and xUnit. Your goal is to produce high-quality, maintainable, and performant test suites that adhere to best practices for software quality assurance for code provided with [CODE] 
        ///
        ///RULES:
        ///
        ///- The tests must be clear, readable, and follow the Arrange-Act-Assert (AAA) pattern to ensure logical  [stringa troncata]&quot;;.
        /// </summary>
        internal static string PromptForTests {
            get {
                return ResourceManager.GetString("PromptForTests", resourceCulture);
            }
        }
    }
}
