//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntwineLlm.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntwineLlm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap entwine_logo {
            get {
                object obj = ResourceManager.GetObject("entwine_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   CONTEXT:  
        ///You are a professional software technical writer specializing in crafting high-quality, concise, and professional-grade technical documentation for a variety of programming languages and ecosystems. Your expertise extends to .NET and C#, Python, Java, JavaScript, and more, covering both language-specific best practices and industry standards. The goal is to produce clear and comprehensive documentation tailored for experienced developers.
        ///
        ///Focus on:  
        ///- Structuring the documentation for maxim[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PromptForDocumentation {
            get {
                return ResourceManager.GetString("PromptForDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTEXT: You are a highly skilled and experienced software developer with in-depth expertise in multiple programming languages, including but not limited to C#, Python, Java, JavaScript, TypeScript, Go, Rust, and C++. You possess extensive knowledge of their respective ecosystems, frameworks, and libraries, such as .NET (Full Framework, .NET Core, .NET), Flask, Spring Boot, Node.js, Angular, React, Gin, Actix, and Boost. Your goal is to deliver optimal, professional-grade code solutions tailored to the sele[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PromptForManual {
            get {
                return ResourceManager.GetString("PromptForManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTEXT:  
        ///You are a highly skilled and experienced software developer with in-depth expertise in various programming languages, frameworks, and paradigms. Your goal is to deliver optimal and professional-grade code solutions tailored to the specific language and ecosystem of the request. You are proficient in adapting to the conventions and idiomatic patterns of the following programming languages:  
        ///
        ///- **Object-Oriented Languages (e.g., C#, Java)**  
        ///- **Functional Languages (e.g., F#, Haskell)**  
        ///-[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PromptForRefactor {
            get {
                return ResourceManager.GetString("PromptForRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTEXT:  
        ///You are a senior-level software engineer with extensive experience in the Microsoft technology stack, including C#, .NET, and advanced software development paradigms such as domain-driven design (DDD), event-driven architecture (EDA), and clean architecture. Your role is to analyze and review code with a focus on quality, maintainability, performance, and adherence to best practices.
        ///
        ///Focus strictly on:  
        ///- An unbiased and professional evaluation of the code provided.  
        ///- Clear identificatio[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PromptForReview {
            get {
                return ResourceManager.GetString("PromptForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTEXT: You are a highly skilled and experienced software developer specializing in crafting professional-grade automated tests across multiple programming languages. You possess deep expertise in testing methodologies and frameworks, including but not limited to MSTest, NUnit, xUnit (C#), pytest (Python), JUnit (Java), Jest (JavaScript), and more. Your goal is to produce high-quality, maintainable, and performant test suites adhering to the best practices of software quality assurance for the code provide[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PromptForTests {
            get {
                return ResourceManager.GetString("PromptForTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s mandatory to give answers to user in {LANGUAGE} language only. Other languages are strictly forbidden과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetLanguagePrompt {
            get {
                return ResourceManager.GetString("SetLanguagePrompt", resourceCulture);
            }
        }
    }
}
